/*
******************************************************************************
File:     main.cpp
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2022-11-21

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include "stm32l0xx.h"

#include "stm32l0xx_hal.h" //Delay
#include "stm32l0xx_hal_gpio.h"
#include "stm32l0xx_hal_gpio_ex.h"

/* Variable statique */
static GPIO_InitTypeDef init ;//variable de ce type pour l’initialisation

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	  uint32_t ii = 0;

	  /* TODO - Add your application code here */
	  /* TODO - Add your application code here */
	     HAL_Init() ; //Initialisation comme ma prise en compte des fonctions comme le Delay.
	    // SystemClock_config();
	     __HAL_RCC_GPIOA_CLK_ENABLE(); //valide la clock GPIOA

	     /*Initialise le port */
	     init.Mode = GPIO_MODE_OUTPUT_PP  ;
	     init.Pull = GPIO_PULLUP;
	     init.Speed = GPIO_SPEED_FREQ_HIGH ;//HIGH, MEDIUM
	     init.Pin = GPIO_PIN_5 ;
	     //INITIALISATION
	     HAL_GPIO_Init(GPIOA, &init) ;


	  while (1)
	  {
	       ii++;
	       HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);
	        	HAL_Delay(5000);
	  }

	  return 0;
}
